// <auto-generated />
namespace BookstoreProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class bookproperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bookproperties));
        
        string IMigrationMetadata.Id
        {
            get { return "202105030328277_book-properties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
